/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JT;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        App A1 = new App();
        System.out.println(A1.getGreeting());
        System.out.println("이거 바꿈");
    }
}
